portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sabina.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

sabina/urls.py
from unicodedata import name
from django.urls import path
from sabina import views
from rest_framework.urlpatterns import format_suffix_patterns
from django.views.generic import TemplateView
from .views import (
    AboutListView,
    HomeListView,
    AboutListAPIView,
    ContactListAPIView,
    ProjectListView,
    EducationListView,
    SkillsListView,
    ContactListView,
    ProjectListAPIView,
    SkillsListAPIView,
    HomeListAPIView,
)



urlpatterns = [
    
    #path('', views.index, name='index'),
    #home section
    path('home/', HomeListView.as_view()),
    path('api/home', HomeListAPIView.as_view(),name="home-api"),
    path('api/home/create', views.HomeList.as_view()),
    path('api/home/<int:pk>/', views.HomeDetail.as_view(),name="detail-api"),

    #About section
    path('about/', AboutListView.as_view()),
    path('api/about', AboutListAPIView.as_view(),name="about-api"),
    path('api/about/create', views.AboutList.as_view()),
    path('api/about/<int:pk>/', views.AboutDetail.as_view(), name="about-detail-api"),
    
    
    #Projects sections
    path('project/', ProjectListView.as_view()),
    path('api/project', ProjectListAPIView.as_view(), name="project-api"),
    path('api/project/create', views.ProjectList.as_view()),
    path('api/project/<int:pk>/', views.ProjectDetail.as_view(), name="project-detail-api"),
   

    #Education section
    path('education/', EducationListView.as_view()),
    path('api/education/create', views.EducationList.as_view(), name="education-api"),
    path('api/education/<int:pk>/', views.EducationDetail.as_view(), name="education-detail-api"),

    #Skills section
    path('skills/', SkillsListView.as_view()),
    path('api/skills', SkillsListAPIView.as_view()),
    path('api/skills/create', views.SkillsList.as_view(), name="skills-api"),
    path('api/skills/<int:pk>/', views.SkillsDetail.as_view()),
    #path('contact/', ContactListView.as_view()),
    path('portfolio/', ProjectListView.as_view()),

    #contact section
    path('contact/', ContactListView.as_view()),
    path('api/contact', ContactListAPIView.as_view()),
    path('api/contact/create', views.ContactList.as_view(), name="contact-api"),
    path('api/contact/<int:pk>/', views.ContactDetail.as_view(), name="contact-detail-api"),

    # path('education/',TemplateView.as_view(template_name="education.html")),
    # path('skills/',TemplateView.as_view(template_name="skills.html")),
    #path('project/',TemplateView.as_view(template_name="projects.html")),
    # path('contact/',TemplateView.as_view(template_name="contact.html")),

    #Index section
    path('index/',TemplateView.as_view(template_name="index.html")),
    
]

urlpatterns = format_suffix_patterns(urlpatterns)

sabina/models.py
from django.db import models

# HOME SECTION

class Home(models.Model):
    name = models.CharField(max_length=20)
    greetings_1 = models.CharField(max_length=15)
    greetings_2 = models.CharField(max_length=15)
    picture = models.ImageField(upload_to='picture/')
    # save time when modified
    updated = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


# ABOUT SECTION
class About(models.Model):
    heading = models.CharField(max_length=50)
    career = models.CharField(max_length=30)
    description = models.TextField(blank=False)
    profile_img = models.ImageField(upload_to='profile/')
    
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.career
 
#one to one field
#Profile section
class Profile(models.Model):
    about = models.ForeignKey(About,
                                on_delete=models.CASCADE)
    social_name = models.CharField(max_length=10)
    link = models.URLField(max_length=200)




# SKILLS SECTION
class Category(models.Model):
    name = models.CharField(max_length=20)

    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Skill'
        verbose_name_plural = 'Skills'

    def __str__(self):
        return self.name

class Skills(models.Model):
    category = models.ForeignKey(Category,
                                on_delete=models.CASCADE)
    skill_name = models.CharField(max_length=20)

    

# PORTFOLIO SECTION
class Project(models.Model):
    image = models.ImageField(upload_to='project/')
    link = models.URLField(max_length=200)

    def __str__(self):
        return f'Project {self.id}'

# Education Section
class Education(models.Model):
    year = models.CharField(max_length=50)
    level = models.CharField(max_length=80)

    def __str__(self):
        return f'Education {self.id}'
    

# Contact Section
class Contact(models.Model):
    phone = models.CharField(max_length=40)
    email = models.CharField(max_length=50)

    def __str__(self):
        return self.phone

sabina/views.py
# from django.shortcuts import render
# from .models import Home, About, Profile, Category, Skills, Project, Education
# from django.views.generic import TemplateView

# #rest framework
# #from django.shortcuts import render



# def index(request):

#      # Home
#     home = Home.objects.latest('updated')

#     # About
#     about = About.objects.latest('updated')
#     profiles = Profile.objects.filter(about=about)

#      # Skills
#     categories = Category.objects.all()

#     # Projects
#     project = Project.objects.all()

#     #Education
#     education = Education.objects.all()

#     context = {
#         'home': home,
#         'about': about,
#         'profiles': profiles,
#         'categories': categories,
#         'project': project,
#         'education': education
#     }

    
#     return render(request, 'index.html', context)

from pipes import Template
from typing import List
from django.shortcuts import render
from django.views import generic
from django.urls import reverse
from django.views.generic.list import ListView
from .models import About, Category, Education, Home, Project, Skills, Contact
from .serializers import AboutSerializer, HomeSerializer, ContactSerializer, ProjectSerializer, EducationSerializer, SkillsSerializer
from rest_framework import generics

from rest_framework.generics import (
    ListAPIView,
    RetrieveUpdateDestroyAPIView
)

from sabina import serializers

#Home Section
class HomeListView(ListView):
    template_name = 'home.html'
    context_object_name = 'home'

    def get_queryset(self):
        return Home.objects.latest('updated')

#create home section
class HomeList(generics.ListCreateAPIView):
    queryset = Home.objects.all()
    serializer_class = HomeSerializer

class HomeDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Home.objects.all()
    serializer_class = HomeSerializer

        
# class HomeListView(ListView):
#     model = Home

#About Section
class AboutListView(ListView):
    template_name = 'about.html'
    context_object_name = 'about'

    def get_queryset(self):
        """Return the last five published questions."""
        return About.objects.latest('updated')
#Create About
class AboutList(generics.ListCreateAPIView):
    queryset = About.objects.all()
    serializer_class = AboutSerializer

#Retrieve about section

class AboutDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = About.objects.all()
    serializer_class = AboutSerializer

#Model viewsset of About
# class AboutModelViewSet(viewsets.ModelViewSet):
#     queryset = About.objects.all()
#     serializer_class = AboutSerializer

# #Create
# class AboutCreateView(ListView):
#     template_name = 'about.html'
#     context_object_name = 'about'

#     def get_queryset(self):
#         return About.objects.latest('created')


#Skills Section
class SkillsListView(ListView):
    template_name = 'skills.html'
    context_object_name = 'skills'

    def get_queryset(self):
        return Skills.objects.all()

#Create skills
class SkillsList(generics.ListCreateAPIView):
    queryset = About.objects.all()
    serializer_class = SkillsSerializer

#Retrieve skills section
class SkillsDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = About.objects.all()
    serializer_class = SkillsSerializer

#Contact Section
class ContactListView(ListView):
    template_name = 'contact.html'
    context_object_name = 'contact'

    def get_queryset(self):
        return Contact.objects.all()

#Create Contact section
class ContactList(generics.ListCreateAPIView):
    queryset = Contact.objects.all()
    serializer_class = ContactSerializer

#Retrieve contact section
class ContactDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Contact.objects.all()
    serializer_class = ContactSerializer
        

#Education section
class EducationListView(ListView):
    template_name = 'education.html'
    context_object_name = 'education'

    def get_queryset(self):
        
        return Education.objects.all()

#Create Education section
class EducationList(generics.ListCreateAPIView):
    queryset = Education.objects.all()
    serializer_class = EducationSerializer

#Retrieve education section
class EducationDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = About.objects.all()
    serializer_class = EducationSerializer



#Projects section
class ProjectListView(ListView):
    template_name = 'projects.html'
    context_object_name = 'project'

    def get_queryset(self):
        project = Project.objects.all()

#Create Project section
class ProjectList(generics.ListCreateAPIView):
    queryset = Project.objects.all()
    serializer_class = ProjectSerializer

#Retrieve project section
class ProjectDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Project.objects.all()
    serializer_class = ProjectSerializer
        
#Api of AboutSerializer
class AboutListAPIView(ListAPIView):
    serializer_class = AboutSerializer
    queryset = About.objects.all()

#Api of ProjectSerializeer
class ProjectListAPIView(ListAPIView):
    serializer_class = ProjectSerializer
    queryset = Project.objects.all()

#Api of SkillsSerializer
class SkillsListAPIView(ListAPIView):
    serializer_class = SkillsSerializer
    queryset = Skills.objects.all()

#Api of HomeSerializer
class HomeListAPIView(ListAPIView):
    serializer_class = HomeSerializer
    queryset = Home.objects.all()

#Api of EducationSerializer
class EducationListAPIView(ListAPIView):
    serializer_class = EducationSerializer
    queryset = Education.objects.all()

#Api of ContactSerializer
class ContactListAPIView(ListAPIView):
    serializer_class = ContactSerializer
    queryset = Contact.objects.all()

# class AboutListView(ListView):
#     model = About

# class SkillsListView(ListView):
#     model = Skills

# class ProjectListView(ListView):
#     model = Project

# class EducationListView(List):
#     model = Education

sabina/templates/about.html
{% comment %} About Section {% endcomment %}
{% load static %}
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- ===== CSS ===== -->
        <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">

        <!-- ===== BOX ICONS ===== -->
        <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>

        <title>About Section</title>
    </head>
    <body>
        <!--===== HEADER =====-->
        <header class="l-header">
            <nav class="nav bd-grid">
                
                <div>
                    <a href="#" class="nav__logo">{{ home.name }}</a>
                </div>

                <div class="nav__menu" id="nav-menu">
                    <ul class="nav__list">
                        <li class="nav__item"><a href="#about" class="nav__link">About</a></li>
                        
                    </ul>
                </div>

                <div class="nav__toggle" id="nav-toggle">
                    <i class='bx bx-menu'></i>
                </div>
            </nav>
        </header>
<section class="about section" id="about">
    <h2 class="section-title">About</h2>

    <div class="about__container bd-grid">
        <div class="about__img">
            <!-- <img src="{% static 'assets/img/Sabina.png' %}" alt=""> -->
            <img src="{{ about.profile_img.url }}" alt="">
        </div>

        <div>
            <h2 class="about__subtitle">{{ about.heading }}</h2>
            <span class="about__profession">{{ about.career }}</span>
            <p class="about__text">{{ about.description }}</p>

            <div class="about__social">

                {% for profile in about.profile_set.all %}
                    <a href="{{ profile.link }}" class="about__social-icon">
                        <i class='bx bxl-{{ profile.social_name }}' ></i>
                    </a>
                {% endfor %}
                
            </div>
        </div>
    </div>
</section>

sabina/templates/contact.html
{% load static %}
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- ===== CSS ===== -->
        <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">

        <!-- ===== BOX ICONS ===== -->
        <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>

        <title>Contact Section</title>
    </head>
    <body>
        <!--===== HEADER =====-->
        <header class="l-header">
            <nav class="nav bd-grid">
                
                <div>
                    <a href="#" class="nav__logo">{{ home.name }}</a>
                </div>

                <div class="nav__menu" id="nav-menu">
                    <ul class="nav__list">
                        <li class="nav__item"><a href="#contact" class="nav__link">Contact</a></li>
                        
                    </ul>
                </div>

                <div class="nav__toggle" id="nav-toggle">
                    <i class='bx bx-menu'></i>
                </div>
            </nav>
        </header>

 <!--===== CONTACT =====-->
 {% comment %} <section class="contact section" id="contact">
    <h2 class="section-title">Contact</h2>

    <div class="contact__container bd-grid">
        <div class="contact__info">
            <h3 class="contact__subtitle">EMAIL</h3>
            <span class="contact__text">Karkisabina869@gmail.com</span>

        </div>

        <div class="contact__info">

            <h3 class="contact__subtitle">PHONE</h3>
            <span class="contact__text">9841053490</span>

        </div>
    </div>
</section>
</main> {% endcomment %}

<section class="contact" id="contact">
    <div class="contact__container bd-grid">
        <h1 class="contact__title"><span>{{ contact.phone }}</span><br>{{ contact.email}}.</h1>

        <div class="contact__scroll">
            <a href="#contact" class="contact__scroll-link"><i class='bx bx-up-arrow-alt' ></i>Scroll down</a>
</section>

sabina/templates/education.html
{% load static %}
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- ===== CSS ===== -->
        <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">

        <!-- ===== BOX ICONS ===== -->
        <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>

        <title>Portfolio responsive complete</title>
    </head>
    <body>
        <!--===== HEADER =====-->
        <header class="l-header">
            <nav class="nav bd-grid">
                
                <div>
                    <a href="#" class="nav__logo">{{ home.name }}</a>
                </div>

                <div class="nav__menu" id="nav-menu">
                    <ul class="nav__list">
                        <li class="nav__item"><a href="#home" class="nav__link active">Home</a></li>
                        <li class="nav__item"><a href="#about" class="nav__link">About</a></li>
                        <li class="nav__item"><a href="#education" class="nav__link">Education</a></li>
                        <li class="nav__item"><a href="#skills" class="nav__link">Skills</a></li>
                        <li class="nav__item"><a href="#portfolio" class="nav__link">Projects</a></li>
                        <li class="nav__item"><a href="#contact" class="nav__link">Contact</a></li>
                        
                    </ul>
                </div>

                <div class="nav__toggle" id="nav-toggle">
                    <i class='bx bx-menu'></i>
                </div>
            </nav>
        </header>
        <div class="education">
            <h2 class="title">Education</h2>
            <ul>
                <li>
                    <h5>2016-2018</h5>
                    <h6>College Degree in Science </h6>
                    <p>DAV College</p>
                </li>
                <li>
                 <h5>2018-2022</h5>
                 <h6>Bachelor's Degree in CSIT </h6>
                 <p>Academia International College</p>
             </li>
            </ul>
        </div>

sabina/templates/home.html
{% load static %}
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- ===== CSS ===== -->
        <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">

        <!-- ===== BOX ICONS ===== -->
        <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>

        <title>Home Section</title>
    </head>
    <body>
        <!--===== HEADER =====-->
        <header class="l-header">
            <nav class="nav bd-grid">
                
                <div>
                    <a href="#" class="nav__logo">{{ home.name }}</a>
                </div>

                <div class="nav__menu" id="nav-menu">
                    <ul class="nav__list">
                        <li class="nav__item"><a href="#home" class="nav__link active">Home</a></li>
                    </ul>
                </div>

                <div class="nav__toggle" id="nav-toggle">
                    <i class='bx bx-menu'></i>
                </div>
            </nav>
        </header>

        <section class="home" id="home">
            <div class="home__container bd-grid">
                <h1 class="home__title"><span>{{ home.greetings_1 }}</span><br>{{ home.greetings_2 }}.</h1>

                <div class="home__scroll">
                    <a href="#about" class="home__scroll-link"><i class='bx bx-up-arrow-alt' ></i>Scroll down</a>
                </div>
                <img src="{{ home.picture.url }}" alt="" class="home__img">
            </div>
        </section>

sabina/templates/index.html
{% load static %}
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- ===== CSS ===== -->
        <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">

        <!-- ===== BOX ICONS ===== -->
        <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>

        <title>Portfolio responsive complete</title>
    </head>
    <body>
        <!--===== HEADER =====-->
        <header class="l-header">
            <nav class="nav bd-grid">
                
                <div>
                    <a href="#" class="nav__logo">{{ home.name }}</a>
                </div>

                <div class="nav__menu" id="nav-menu">
                    <ul class="nav__list">
                        <li class="nav__item"><a href="/home/" class="nav__link active">Home</a></li>
                        <li class="nav__item"><a href="/about/" class="nav__link">About</a></li>
                        <li class="nav__item"><a href="/education/" class="nav__link">Education</a></li>
                        <li class="nav__item"><a href="/skills/" class="nav__link">Skills</a></li>
                        <li class="nav__item"><a href="/portfolio/" class="nav__link">Projects</a></li>
                        <li class="nav__item"><a href="/contact/" class="nav__link">Contact</a></li>
                        
                    </ul>
                </div>

                <div class="nav__toggle" id="nav-toggle">
                    <i class='bx bx-menu'></i>
                </div>
            </nav>
        </header>

        <main class="l-main">
            <!--===== HOME =====-->
            <section class="home" id="home">
                <div class="home__container bd-grid">
                    <h1 class="home__title"><span>{{ home.greetings_1 }}</span><br>{{ home.greetings_2 }}.</h1>

                    <div class="home__scroll">
                        <a href="#about" class="home__scroll-link"><i class='bx bx-up-arrow-alt' ></i>Scroll down</a>
                    </div>
                    <img src="{{ home.picture.url }}" alt="" class="home__img">
                </div>
            </section>

            <!--===== ABOUT =====-->
            <section class="about section" id="about">
                <h2 class="section-title">About</h2>

                <div class="about__container bd-grid">
                    <div class="about__img">
                        <!-- <img src="{% static 'assets/img/Sabina.png' %}" alt=""> -->
                        <img src="{{ about.profile_img.url }}" alt="">
                    </div>

                    <div>
                        <h2 class="about__subtitle">{{ about.heading }}</h2>
                        <span class="about__profession">{{ about.career }}</span>
                        <p class="about__text">{{ about.description }}</p>

                        <div class="about__social">

                            {% for profile in about.profile_set.all %}
                                <a href="{{ profile.link }}" class="about__social-icon">
                                    <i class='bx bxl-{{ profile.social_name }}' ></i>
                                </a>
                            {% endfor %}
                            
                        </div>
                    </div>
                </div>
            </section>

             <!--===== EDUCATION =====-->
             <div class="education">
                <h2 class="title">Education</h2>
                <ul>
                    <li>
                        <h5>2016-2018</h5>
                        <h6>College Degree in Science </h6>
                        <p>DAV College</p>
                    </li>
                    <li>
                     <h5>2018-2022</h5>
                     <h6>Bachelor's Degree in CSIT </h6>
                     <p>Academia International College</p>
                 </li>
                </ul>
            </div>
             {% comment %} <section class="education section" id="education">
                <h2 class="education-title">Education</h2>
                <div class="skills__box">
                
                
                <div class="education__container bd-grid">
                    <h2 class="education__subtitle">{{ education.year }}</h2>



                    {% for education in education %}
                    
                    <div class="education__year">
                       

                    {% endfor %}
                    </div>
                    
                </div>
                
            </section> {% endcomment %}

             
            <!--===== SKILLS =====-->
            <section class="skills section" id="skills">
                <h2 class="section-title">Skills</h2>

                <div class="skills__container bd-grid">
                    <div class="skills__box">
                        {% for category in categories %}
                        <h3 class="skills__subtitle">{{category.name}}</h3>
                            {% for skills in category.skills_set.all %}
                            
                                <span class="skills__name">{{skills.skill_name}}</span>
                            {% endfor %}
                        {% endfor %}
                        
                        
                    </div>

                    <div class="skills__img">
                        <img src="{% static 'assets/img/skill.jpg' %}" alt="">
                    </div>
                </div>
            </section>

            <!--===== Projects =====-->
            <section class="project section" id="project">
                <h2 class="section-title">Projects</h2>

                
                <div class="project__container bd-grid">

                    {% for project in project %}
                    
                    <div class="project__img">
                        <img src="{{ project.image.url }}" alt="">

                        <div class="project__link">
                            <a href="{{ project.link }}" class="project__link-name">View details</a>
                        </div>
                    </div>

                    {% endfor %}
                    
                </div>
                
            </section>

            

            <!--===== CONTACT =====-->
            <section class="contact section" id="contact">
                <h2 class="section-title">Contact</h2>

                <div class="contact__container bd-grid">
                    <div class="contact__info">
                        <h3 class="contact__subtitle">EMAIL</h3>
                        <span class="contact__text">Karkisabina869@gmail.com</span>

                    </div>

                    <div class="contact__info">

                        <h3 class="contact__subtitle">PHONE</h3>
                        <span class="contact__text">9841053490</span>

                    </div>
                </div>
            </section>
        </main>

        <!--===== FOOTER =====-->
        <footer class="footer section">
            <div class="footer__container bd-grid">
                <div class="footer__data">
                    <h2 class="footer__title">SABINA KARKI</h2>
                    <p class="footer__text">I'm Sabina Karki and this is my personal website</p>
                </div>

                <div class="footer__data">
                    <h2 class="footer__title">EXPLORE</h2>
                    <ul>
                        <li><a href="#home" class="footer__link">Home</a></li>
                        <li><a href="#about" class="footer__link">About</a></li>
                        <li><a href="#about" class="footer__link">Education</a></li>
                        <li><a href="#skills" class="footer__link">Skills</a></li>
                        <li><a href="#portfolio" class="footer__link">Projects</a></li>
                        <li><a href="#Contact" class="footer__link">Contact</a></li>
                    </ul>
                </div>
                
                <div class="footer__data">
                    <h2 class="footer__title">FOLLOW</h2>
                    <a href="#" class="footer__social"><i class='bx bxl-facebook' ></i></a>
                    <a href="#" class="footer__social"><i class='bx bxl-instagram' ></i></a>
                    <a href="#" class="footer__social"><i class='bx bxl-twitter' ></i></a>
                </div>


            </div>
        </footer>

        <!--===== SCROLL REVEAL =====-->
        <script src="https://unpkg.com/scrollreveal"></script>

        <!--===== MAIN JS =====-->
        <script src="{% static 'assets/js/main.js' %}"></script>
    </body>
</html>




sabina/templates/skills.html
{% comment %} Skills section {% endcomment %}
{% load static %}
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- ===== CSS ===== -->
        <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">

        <!-- ===== BOX ICONS ===== -->
        <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>

        <title>Skills</title>
    </head>
    <body>
        <!--===== HEADER =====-->
        <header class="l-header">
            <nav class="nav bd-grid">
                
                <div>
                    <a href="#" class="nav__logo">{{ home.name }}</a>
                </div>

                <div class="nav__menu" id="nav-menu">
                    <ul class="nav__list">
                        <li class="nav__item"><a href="#skills" class="nav__link">Skills</a></li>  
                    </ul>
                </div>

                <div class="nav__toggle" id="nav-toggle">
                    <i class='bx bx-menu'></i>
                </div>
            </nav>
        </header>
<section class="skills section" id="skills">
    <h2 class="section-title">Skills</h2>

    <div class="skills__container bd-grid">
        <div class="skills__box">
            {% for category in categories %}
            <h3 class="skills__subtitle">{{category.name}}</h3>
                {% for skills in category.skills_set.all %}
                
                    <span class="skills__name">{{skills.skill_name}}</span>
                {% endfor %}
            {% endfor %}
            
            
        </div>

        <div class="skills__img">
            <img src="{% static 'assets/img/skill.jpg' %}" alt="">
        </div>
    </div>
</section>